[2024-03-01 10:56:50,296] {processor.py:153} INFO - Started process (PID=11852) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:56:50,296] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 10:56:50,297] {logging_mixin.py:115} INFO - [2024-03-01 10:56:50,297] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:56:50,298] {logging_mixin.py:115} INFO - [2024-03-01 10:56:50,298] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 8
    )
    ^
SyntaxError: invalid syntax
[2024-03-01 10:56:50,298] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:56:50,324] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.029 seconds
[2024-03-01 10:57:29,138] {processor.py:153} INFO - Started process (PID=12104) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:57:29,140] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 10:57:29,141] {logging_mixin.py:115} INFO - [2024-03-01 10:57:29,141] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:57:29,143] {logging_mixin.py:115} INFO - [2024-03-01 10:57:29,142] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 10
    
    ^
IndentationError: expected an indented block
[2024-03-01 10:57:29,143] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:57:29,177] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.042 seconds
[2024-03-01 10:58:01,088] {processor.py:153} INFO - Started process (PID=12312) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:58:01,090] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 10:58:01,090] {logging_mixin.py:115} INFO - [2024-03-01 10:58:01,090] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:58:01,092] {logging_mixin.py:115} INFO - [2024-03-01 10:58:01,091] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 10
    
    ^
IndentationError: expected an indented block
[2024-03-01 10:58:01,092] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:58:01,114] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.029 seconds
[2024-03-01 10:58:36,625] {processor.py:153} INFO - Started process (PID=12539) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:58:36,627] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 10:58:36,627] {logging_mixin.py:115} INFO - [2024-03-01 10:58:36,627] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:58:36,629] {logging_mixin.py:115} INFO - [2024-03-01 10:58:36,628] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 10
    
    ^
IndentationError: expected an indented block
[2024-03-01 10:58:36,629] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:58:36,650] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 10:59:08,161] {processor.py:153} INFO - Started process (PID=12751) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:59:08,162] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 10:59:08,162] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,162] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:59:08,168] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:59:08,230] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,230] {manager.py:508} INFO - Created Permission View: can delete on DAG:dados_climaticos
[2024-03-01 10:59:08,246] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,246] {manager.py:508} INFO - Created Permission View: can edit on DAG:dados_climaticos
[2024-03-01 10:59:08,257] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,257] {manager.py:508} INFO - Created Permission View: can read on DAG:dados_climaticos
[2024-03-01 10:59:08,257] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,257] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 10:59:08,263] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,262] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2024-03-01 10:59:08,271] {logging_mixin.py:115} INFO - [2024-03-01 10:59:08,271] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 10:59:08,295] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.137 seconds
[2024-03-01 10:59:39,993] {processor.py:153} INFO - Started process (PID=12958) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:59:39,994] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 10:59:39,994] {logging_mixin.py:115} INFO - [2024-03-01 10:59:39,994] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:59:40,000] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 10:59:40,046] {logging_mixin.py:115} INFO - [2024-03-01 10:59:40,046] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 10:59:40,063] {logging_mixin.py:115} INFO - [2024-03-01 10:59:40,063] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 10:59:40,085] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.094 seconds
[2024-03-01 11:00:12,524] {processor.py:153} INFO - Started process (PID=13171) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:00:12,528] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:00:12,529] {logging_mixin.py:115} INFO - [2024-03-01 11:00:12,529] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:00:12,533] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:00:12,563] {logging_mixin.py:115} INFO - [2024-03-01 11:00:12,563] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:00:12,574] {logging_mixin.py:115} INFO - [2024-03-01 11:00:12,574] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:00:12,590] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.068 seconds
[2024-03-01 11:00:46,261] {processor.py:153} INFO - Started process (PID=13462) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:00:46,263] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:00:46,263] {logging_mixin.py:115} INFO - [2024-03-01 11:00:46,263] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:00:46,268] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:00:46,301] {logging_mixin.py:115} INFO - [2024-03-01 11:00:46,300] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:00:46,312] {logging_mixin.py:115} INFO - [2024-03-01 11:00:46,312] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:00:46,328] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.069 seconds
[2024-03-01 11:01:21,949] {processor.py:153} INFO - Started process (PID=13692) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:01:21,953] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:01:21,954] {logging_mixin.py:115} INFO - [2024-03-01 11:01:21,954] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:01:21,955] {logging_mixin.py:115} INFO - [2024-03-01 11:01:21,955] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 3
    from airflow.operators.pyt
                              ^
SyntaxError: invalid syntax
[2024-03-01 11:01:21,956] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:01:21,972] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.025 seconds
[2024-03-01 11:01:53,035] {processor.py:153} INFO - Started process (PID=13898) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:01:53,040] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:01:53,041] {logging_mixin.py:115} INFO - [2024-03-01 11:01:53,041] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:01:53,048] {logging_mixin.py:115} INFO - [2024-03-01 11:01:53,047] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 18, in <module>
    task_
NameError: name 'task_' is not defined
[2024-03-01 11:01:53,048] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:01:53,070] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.036 seconds
[2024-03-01 11:02:23,313] {processor.py:153} INFO - Started process (PID=14098) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:02:23,317] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:02:23,318] {logging_mixin.py:115} INFO - [2024-03-01 11:02:23,318] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:02:23,326] {logging_mixin.py:115} INFO - [2024-03-01 11:02:23,325] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 19, in <module>
    python_callable= extrai_dados
NameError: name 'extrai_dados' is not defined
[2024-03-01 11:02:23,326] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:02:23,342] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.031 seconds
[2024-03-01 11:02:57,872] {processor.py:153} INFO - Started process (PID=14325) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:02:57,876] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:02:57,877] {logging_mixin.py:115} INFO - [2024-03-01 11:02:57,877] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:02:57,884] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:02:57,915] {logging_mixin.py:115} INFO - [2024-03-01 11:02:57,915] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:02:57,929] {logging_mixin.py:115} INFO - [2024-03-01 11:02:57,929] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:02:57,958] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.088 seconds
[2024-03-01 11:03:30,162] {processor.py:153} INFO - Started process (PID=14533) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:03:30,162] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:03:30,162] {logging_mixin.py:115} INFO - [2024-03-01 11:03:30,162] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:03:30,171] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:03:30,186] {logging_mixin.py:115} INFO - [2024-03-01 11:03:30,186] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:03:30,203] {logging_mixin.py:115} INFO - [2024-03-01 11:03:30,203] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:03:30,219] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.059 seconds
[2024-03-01 11:04:01,789] {processor.py:153} INFO - Started process (PID=14744) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:04:01,794] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:04:01,794] {logging_mixin.py:115} INFO - [2024-03-01 11:04:01,794] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:04:01,800] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:04:01,811] {logging_mixin.py:115} INFO - [2024-03-01 11:04:01,811] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:04:01,825] {logging_mixin.py:115} INFO - [2024-03-01 11:04:01,825] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:04:01,840] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.052 seconds
[2024-03-01 11:04:33,752] {processor.py:153} INFO - Started process (PID=14952) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:04:33,753] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:04:33,754] {logging_mixin.py:115} INFO - [2024-03-01 11:04:33,754] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:04:33,761] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:04:33,771] {logging_mixin.py:115} INFO - [2024-03-01 11:04:33,771] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:04:33,785] {logging_mixin.py:115} INFO - [2024-03-01 11:04:33,785] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:04:33,799] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.049 seconds
[2024-03-01 11:05:04,613] {processor.py:153} INFO - Started process (PID=15157) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:05:04,615] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:05:04,615] {logging_mixin.py:115} INFO - [2024-03-01 11:05:04,615] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:05:04,622] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:05:04,632] {logging_mixin.py:115} INFO - [2024-03-01 11:05:04,632] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:05:04,646] {logging_mixin.py:115} INFO - [2024-03-01 11:05:04,646] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:05:04,663] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.052 seconds
[2024-03-01 11:05:36,537] {processor.py:153} INFO - Started process (PID=15371) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:05:36,541] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:05:36,541] {logging_mixin.py:115} INFO - [2024-03-01 11:05:36,541] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:05:36,548] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:05:36,558] {logging_mixin.py:115} INFO - [2024-03-01 11:05:36,558] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:05:36,572] {logging_mixin.py:115} INFO - [2024-03-01 11:05:36,572] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:05:36,590] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.055 seconds
[2024-03-01 11:06:10,946] {processor.py:153} INFO - Started process (PID=15598) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:06:10,950] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:06:10,951] {logging_mixin.py:115} INFO - [2024-03-01 11:06:10,950] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:06:10,957] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:06:10,969] {logging_mixin.py:115} INFO - [2024-03-01 11:06:10,969] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:06:10,984] {logging_mixin.py:115} INFO - [2024-03-01 11:06:10,984] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:06:10,999] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.055 seconds
[2024-03-01 11:06:41,443] {processor.py:153} INFO - Started process (PID=15798) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:06:41,444] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:06:41,445] {logging_mixin.py:115} INFO - [2024-03-01 11:06:41,445] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:06:41,450] {logging_mixin.py:115} INFO - [2024-03-01 11:06:41,450] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:06:41,450] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:06:41,469] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.028 seconds
[2024-03-01 11:07:13,248] {processor.py:153} INFO - Started process (PID=16011) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:07:13,252] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:07:13,253] {logging_mixin.py:115} INFO - [2024-03-01 11:07:13,253] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:07:13,257] {logging_mixin.py:115} INFO - [2024-03-01 11:07:13,257] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:07:13,257] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:07:13,277] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.031 seconds
[2024-03-01 11:07:48,105] {processor.py:153} INFO - Started process (PID=16245) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:07:48,109] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:07:48,110] {logging_mixin.py:115} INFO - [2024-03-01 11:07:48,110] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:07:48,115] {logging_mixin.py:115} INFO - [2024-03-01 11:07:48,114] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:07:48,115] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:07:48,134] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.031 seconds
[2024-03-01 11:08:21,280] {processor.py:153} INFO - Started process (PID=16463) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:08:21,284] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:08:21,285] {logging_mixin.py:115} INFO - [2024-03-01 11:08:21,285] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:08:21,290] {logging_mixin.py:115} INFO - [2024-03-01 11:08:21,289] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:08:21,290] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:08:21,308] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.029 seconds
[2024-03-01 11:08:51,942] {processor.py:153} INFO - Started process (PID=16666) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:08:51,946] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:08:51,946] {logging_mixin.py:115} INFO - [2024-03-01 11:08:51,946] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:08:51,950] {logging_mixin.py:115} INFO - [2024-03-01 11:08:51,950] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:08:51,950] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:08:51,967] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:09:25,678] {processor.py:153} INFO - Started process (PID=16890) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:09:25,681] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:09:25,682] {logging_mixin.py:115} INFO - [2024-03-01 11:09:25,682] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:09:25,683] {logging_mixin.py:115} INFO - [2024-03-01 11:09:25,683] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 23
    data_inicio = datetime.today()
IndentationError: expected an indented block
[2024-03-01 11:09:25,684] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:09:25,704] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.028 seconds
[2024-03-01 11:09:59,952] {processor.py:153} INFO - Started process (PID=17109) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:09:59,956] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:09:59,957] {logging_mixin.py:115} INFO - [2024-03-01 11:09:59,957] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:09:59,961] {logging_mixin.py:115} INFO - [2024-03-01 11:09:59,961] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:09:59,961] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:09:59,977] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:10:33,772] {processor.py:153} INFO - Started process (PID=17239) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:10:33,776] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:10:33,776] {logging_mixin.py:115} INFO - [2024-03-01 11:10:33,776] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:10:33,781] {logging_mixin.py:115} INFO - [2024-03-01 11:10:33,780] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:10:33,781] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:10:33,797] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:11:05,994] {processor.py:153} INFO - Started process (PID=17363) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:11:05,995] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:11:05,996] {logging_mixin.py:115} INFO - [2024-03-01 11:11:05,996] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:11:06,002] {logging_mixin.py:115} INFO - [2024-03-01 11:11:06,001] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:11:06,002] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:11:06,019] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:11:36,393] {processor.py:153} INFO - Started process (PID=17486) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:11:36,397] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:11:36,397] {logging_mixin.py:115} INFO - [2024-03-01 11:11:36,397] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:11:36,402] {logging_mixin.py:115} INFO - [2024-03-01 11:11:36,401] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-01 11:11:36,402] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:11:36,420] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.029 seconds
[2024-03-01 11:12:10,455] {processor.py:153} INFO - Started process (PID=17617) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:12:10,457] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:12:10,457] {logging_mixin.py:115} INFO - [2024-03-01 11:12:10,457] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:12:10,459] {logging_mixin.py:115} INFO - [2024-03-01 11:12:10,459] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 39
    op_kwargs= 
    ^
SyntaxError: invalid syntax
[2024-03-01 11:12:10,459] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:12:10,479] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:12:41,329] {processor.py:153} INFO - Started process (PID=17739) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:12:41,333] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:12:41,334] {logging_mixin.py:115} INFO - [2024-03-01 11:12:41,334] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:12:41,335] {logging_mixin.py:115} INFO - [2024-03-01 11:12:41,335] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 39
    op_kwargs= {'data_interval_end': }
    ^
SyntaxError: invalid syntax
[2024-03-01 11:12:41,336] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:12:41,353] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.025 seconds
[2024-03-01 11:13:11,600] {processor.py:153} INFO - Started process (PID=17853) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:13:11,605] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:13:11,605] {logging_mixin.py:115} INFO - [2024-03-01 11:13:11,605] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:13:11,607] {logging_mixin.py:115} INFO - [2024-03-01 11:13:11,607] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 39
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:13:11,607] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:13:11,626] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.028 seconds
[2024-03-01 11:13:43,068] {processor.py:153} INFO - Started process (PID=17976) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:13:43,069] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:13:43,070] {logging_mixin.py:115} INFO - [2024-03-01 11:13:43,070] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:13:43,072] {logging_mixin.py:115} INFO - [2024-03-01 11:13:43,071] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 39
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:13:43,072] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:13:43,090] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.025 seconds
[2024-03-01 11:14:13,883] {processor.py:153} INFO - Started process (PID=18098) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:14:13,885] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:14:13,885] {logging_mixin.py:115} INFO - [2024-03-01 11:14:13,885] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:14:13,888] {logging_mixin.py:115} INFO - [2024-03-01 11:14:13,887] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 40
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:14:13,888] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:14:13,905] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.024 seconds
[2024-03-01 11:14:47,024] {processor.py:153} INFO - Started process (PID=18227) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:14:47,029] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:14:47,029] {logging_mixin.py:115} INFO - [2024-03-01 11:14:47,029] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:14:47,031] {logging_mixin.py:115} INFO - [2024-03-01 11:14:47,031] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 40
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:14:47,031] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:14:47,049] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:15:17,801] {processor.py:153} INFO - Started process (PID=18664) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:15:17,803] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:15:17,803] {logging_mixin.py:115} INFO - [2024-03-01 11:15:17,803] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:15:17,807] {logging_mixin.py:115} INFO - [2024-03-01 11:15:17,805] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 38
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:15:17,807] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:15:17,835] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.036 seconds
[2024-03-01 11:15:53,916] {processor.py:153} INFO - Started process (PID=18855) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:15:53,920] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:15:53,920] {logging_mixin.py:115} INFO - [2024-03-01 11:15:53,920] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:15:53,922] {logging_mixin.py:115} INFO - [2024-03-01 11:15:53,922] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 38
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:15:53,922] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:15:53,940] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.026 seconds
[2024-03-01 11:16:27,164] {processor.py:153} INFO - Started process (PID=19103) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:16:27,170] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:16:27,171] {logging_mixin.py:115} INFO - [2024-03-01 11:16:27,171] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:16:27,173] {logging_mixin.py:115} INFO - [2024-03-01 11:16:27,173] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 39
    op_kwargs= {'data_interval_end': '{{data_interval_end.strftime("%Y-%m-%d")}}'}
    ^
SyntaxError: invalid syntax
[2024-03-01 11:16:27,174] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:16:27,191] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.028 seconds
[2024-03-01 11:17:01,277] {processor.py:153} INFO - Started process (PID=19254) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:17:01,281] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:17:01,282] {logging_mixin.py:115} INFO - [2024-03-01 11:17:01,282] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:17:01,696] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:17:01,722] {logging_mixin.py:115} INFO - [2024-03-01 11:17:01,722] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:17:01,732] {logging_mixin.py:115} INFO - [2024-03-01 11:17:01,732] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:17:01,756] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.481 seconds
[2024-03-01 11:17:34,649] {processor.py:153} INFO - Started process (PID=19399) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:17:34,650] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:17:34,650] {logging_mixin.py:115} INFO - [2024-03-01 11:17:34,650] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:17:35,051] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:17:35,081] {logging_mixin.py:115} INFO - [2024-03-01 11:17:35,080] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:17:35,097] {logging_mixin.py:115} INFO - [2024-03-01 11:17:35,096] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:17:35,123] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.476 seconds
[2024-03-01 11:18:21,351] {processor.py:153} INFO - Started process (PID=19603) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:18:21,353] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:18:21,353] {logging_mixin.py:115} INFO - [2024-03-01 11:18:21,353] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:18:21,580] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:18:21,587] {logging_mixin.py:115} INFO - [2024-03-01 11:18:21,587] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:18:21,598] {logging_mixin.py:115} INFO - [2024-03-01 11:18:21,598] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:18:21,617] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.270 seconds
[2024-03-01 11:18:54,180] {processor.py:153} INFO - Started process (PID=19785) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:18:54,183] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:18:54,184] {logging_mixin.py:115} INFO - [2024-03-01 11:18:54,184] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:18:54,439] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:18:54,448] {logging_mixin.py:115} INFO - [2024-03-01 11:18:54,448] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:18:54,460] {logging_mixin.py:115} INFO - [2024-03-01 11:18:54,460] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:18:54,475] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.297 seconds
[2024-03-01 11:19:28,532] {processor.py:153} INFO - Started process (PID=19997) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:19:28,537] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:19:28,537] {logging_mixin.py:115} INFO - [2024-03-01 11:19:28,537] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:19:28,778] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:19:28,785] {logging_mixin.py:115} INFO - [2024-03-01 11:19:28,785] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:19:28,796] {logging_mixin.py:115} INFO - [2024-03-01 11:19:28,796] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-10-03T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2024-03-01 11:19:28,808] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.280 seconds
[2024-03-01 11:20:07,837] {processor.py:153} INFO - Started process (PID=20372) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:20:07,839] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:20:07,839] {logging_mixin.py:115} INFO - [2024-03-01 11:20:07,839] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:20:08,082] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:20:08,090] {logging_mixin.py:115} INFO - [2024-03-01 11:20:08,090] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:20:08,103] {logging_mixin.py:115} INFO - [2024-03-01 11:20:08,103] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-02-06T00:00:00+00:00, run_after=2023-02-13T00:00:00+00:00
[2024-03-01 11:20:08,119] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.284 seconds
[2024-03-01 11:20:52,933] {processor.py:153} INFO - Started process (PID=20808) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:20:52,934] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:20:52,935] {logging_mixin.py:115} INFO - [2024-03-01 11:20:52,935] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:20:53,201] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:20:53,209] {logging_mixin.py:115} INFO - [2024-03-01 11:20:53,208] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:20:53,222] {logging_mixin.py:115} INFO - [2024-03-01 11:20:53,222] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2023-07-03T00:00:00+00:00, run_after=2023-07-10T00:00:00+00:00
[2024-03-01 11:20:53,240] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.310 seconds
[2024-03-01 11:21:42,194] {processor.py:153} INFO - Started process (PID=21271) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:21:42,195] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:21:42,196] {logging_mixin.py:115} INFO - [2024-03-01 11:21:42,196] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:21:42,465] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:21:42,492] {logging_mixin.py:115} INFO - [2024-03-01 11:21:42,491] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:21:42,497] {logging_mixin.py:115} INFO - [2024-03-01 11:21:42,497] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2024-03-01 11:21:42,506] {logging_mixin.py:115} INFO - [2024-03-01 11:21:42,506] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:21:42,525] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.334 seconds
[2024-03-01 11:22:14,417] {processor.py:153} INFO - Started process (PID=21539) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:22:14,421] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:22:14,421] {logging_mixin.py:115} INFO - [2024-03-01 11:22:14,421] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:22:14,671] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:22:14,680] {logging_mixin.py:115} INFO - [2024-03-01 11:22:14,680] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:22:14,691] {logging_mixin.py:115} INFO - [2024-03-01 11:22:14,691] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-10-03T00:00:00+00:00, run_after=2022-10-10T00:00:00+00:00
[2024-03-01 11:22:14,709] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.293 seconds
[2024-03-01 11:23:05,790] {processor.py:153} INFO - Started process (PID=21978) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:23:05,791] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:23:05,792] {logging_mixin.py:115} INFO - [2024-03-01 11:23:05,792] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:23:06,026] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:23:06,034] {logging_mixin.py:115} INFO - [2024-03-01 11:23:06,034] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:23:06,046] {logging_mixin.py:115} INFO - [2024-03-01 11:23:06,046] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-12-12T00:00:00+00:00, run_after=2022-12-19T00:00:00+00:00
[2024-03-01 11:23:06,063] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.275 seconds
[2024-03-01 11:23:40,171] {processor.py:153} INFO - Started process (PID=22117) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:23:40,175] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:23:40,176] {logging_mixin.py:115} INFO - [2024-03-01 11:23:40,176] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:23:40,409] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:23:40,433] {logging_mixin.py:115} INFO - [2024-03-01 11:23:40,433] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:23:40,439] {logging_mixin.py:115} INFO - [2024-03-01 11:23:40,439] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2024-03-01 11:23:40,446] {logging_mixin.py:115} INFO - [2024-03-01 11:23:40,446] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:23:40,464] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.295 seconds
[2024-03-01 11:24:13,912] {processor.py:153} INFO - Started process (PID=22247) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:24:13,914] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:24:13,915] {logging_mixin.py:115} INFO - [2024-03-01 11:24:13,915] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:24:14,134] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:24:14,142] {logging_mixin.py:115} INFO - [2024-03-01 11:24:14,142] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:24:14,153] {logging_mixin.py:115} INFO - [2024-03-01 11:24:14,153] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:24:14,169] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.258 seconds
[2024-03-01 11:24:48,122] {processor.py:153} INFO - Started process (PID=22379) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:24:48,123] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:24:48,124] {logging_mixin.py:115} INFO - [2024-03-01 11:24:48,124] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:24:48,340] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:24:48,348] {logging_mixin.py:115} INFO - [2024-03-01 11:24:48,348] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:24:48,358] {logging_mixin.py:115} INFO - [2024-03-01 11:24:48,358] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:24:48,376] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.256 seconds
[2024-03-01 11:25:21,867] {processor.py:153} INFO - Started process (PID=22523) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:25:21,871] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:25:21,872] {logging_mixin.py:115} INFO - [2024-03-01 11:25:21,872] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:25:22,093] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:25:22,101] {logging_mixin.py:115} INFO - [2024-03-01 11:25:22,101] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:25:22,112] {logging_mixin.py:115} INFO - [2024-03-01 11:25:22,112] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:25:22,128] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.263 seconds
[2024-03-01 11:25:55,222] {processor.py:153} INFO - Started process (PID=22655) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:25:55,223] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:25:55,224] {logging_mixin.py:115} INFO - [2024-03-01 11:25:55,224] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:25:55,464] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:25:55,471] {logging_mixin.py:115} INFO - [2024-03-01 11:25:55,471] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:25:55,484] {logging_mixin.py:115} INFO - [2024-03-01 11:25:55,484] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:25:55,503] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.283 seconds
[2024-03-01 11:26:32,571] {processor.py:153} INFO - Started process (PID=22799) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:26:32,576] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:26:32,577] {logging_mixin.py:115} INFO - [2024-03-01 11:26:32,576] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:26:32,808] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:26:32,816] {logging_mixin.py:115} INFO - [2024-03-01 11:26:32,816] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:26:32,826] {logging_mixin.py:115} INFO - [2024-03-01 11:26:32,826] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:26:32,844] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.275 seconds
[2024-03-01 11:27:06,998] {processor.py:153} INFO - Started process (PID=22935) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:27:06,999] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:27:07,000] {logging_mixin.py:115} INFO - [2024-03-01 11:27:07,000] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:27:07,003] {logging_mixin.py:115} INFO - [2024-03-01 11:27:07,002] {dagbag.py:320} ERROR - Failed to import: /home/luan/Documents/airflowalura/dags/dados_climaticos.py
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 37
    task_id= 'extrai_dados',
    ^
SyntaxError: invalid syntax
[2024-03-01 11:27:07,003] {processor.py:653} WARNING - No viable dags retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:27:07,022] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.027 seconds
[2024-03-01 11:27:38,414] {processor.py:153} INFO - Started process (PID=23060) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:27:38,416] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:27:38,416] {logging_mixin.py:115} INFO - [2024-03-01 11:27:38,416] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:27:38,654] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:27:38,680] {logging_mixin.py:115} INFO - [2024-03-01 11:27:38,679] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:27:38,685] {logging_mixin.py:115} INFO - [2024-03-01 11:27:38,685] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2024-03-01 11:27:38,692] {logging_mixin.py:115} INFO - [2024-03-01 11:27:38,691] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:27:38,714] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.301 seconds
[2024-03-01 11:28:50,306] {processor.py:153} INFO - Started process (PID=23650) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:28:50,307] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:28:50,308] {logging_mixin.py:115} INFO - [2024-03-01 11:28:50,308] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:28:50,542] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:28:50,550] {logging_mixin.py:115} INFO - [2024-03-01 11:28:50,550] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:28:50,563] {logging_mixin.py:115} INFO - [2024-03-01 11:28:50,562] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-21T00:00:00+00:00, run_after=2022-11-28T00:00:00+00:00
[2024-03-01 11:28:50,597] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.293 seconds
[2024-03-01 11:29:20,847] {processor.py:153} INFO - Started process (PID=23821) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:29:20,851] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:29:20,851] {logging_mixin.py:115} INFO - [2024-03-01 11:29:20,851] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:29:21,116] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:29:21,144] {logging_mixin.py:115} INFO - [2024-03-01 11:29:21,144] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:29:21,150] {logging_mixin.py:115} INFO - [2024-03-01 11:29:21,150] {dag.py:2398} INFO - Creating ORM DAG for dados_climaticos
[2024-03-01 11:29:21,159] {logging_mixin.py:115} INFO - [2024-03-01 11:29:21,159] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-08-22T00:00:00+00:00, run_after=2022-08-29T00:00:00+00:00
[2024-03-01 11:29:21,177] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.331 seconds
[2024-03-01 11:30:25,172] {processor.py:153} INFO - Started process (PID=24358) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:30:25,174] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:30:25,174] {logging_mixin.py:115} INFO - [2024-03-01 11:30:25,174] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:30:25,417] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:30:25,426] {logging_mixin.py:115} INFO - [2024-03-01 11:30:25,426] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:30:25,440] {logging_mixin.py:115} INFO - [2024-03-01 11:30:25,440] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-14T00:00:00+00:00, run_after=2022-11-21T00:00:00+00:00
[2024-03-01 11:30:25,458] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.287 seconds
[2024-03-01 11:30:56,436] {processor.py:153} INFO - Started process (PID=24530) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:30:56,440] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:30:56,440] {logging_mixin.py:115} INFO - [2024-03-01 11:30:56,440] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:30:56,683] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:30:56,692] {logging_mixin.py:115} INFO - [2024-03-01 11:30:56,692] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:30:56,704] {logging_mixin.py:115} INFO - [2024-03-01 11:30:56,704] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:30:56,720] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.286 seconds
[2024-03-01 11:31:28,636] {processor.py:153} INFO - Started process (PID=24657) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:31:28,640] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:31:28,641] {logging_mixin.py:115} INFO - [2024-03-01 11:31:28,641] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:31:28,910] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:31:28,919] {logging_mixin.py:115} INFO - [2024-03-01 11:31:28,919] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:31:28,933] {logging_mixin.py:115} INFO - [2024-03-01 11:31:28,933] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:31:28,947] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.312 seconds
[2024-03-01 11:32:03,128] {processor.py:153} INFO - Started process (PID=24796) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:32:03,129] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:32:03,129] {logging_mixin.py:115} INFO - [2024-03-01 11:32:03,129] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:32:03,376] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:32:03,384] {logging_mixin.py:115} INFO - [2024-03-01 11:32:03,384] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:32:03,397] {logging_mixin.py:115} INFO - [2024-03-01 11:32:03,397] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:32:03,414] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.288 seconds
[2024-03-01 11:32:37,930] {processor.py:153} INFO - Started process (PID=24931) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:32:37,931] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:32:37,932] {logging_mixin.py:115} INFO - [2024-03-01 11:32:37,932] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:32:38,306] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:32:38,315] {logging_mixin.py:115} INFO - [2024-03-01 11:32:38,315] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:32:38,328] {logging_mixin.py:115} INFO - [2024-03-01 11:32:38,328] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:32:38,343] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.416 seconds
[2024-03-01 11:33:12,680] {processor.py:153} INFO - Started process (PID=25069) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:33:12,682] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:33:12,682] {logging_mixin.py:115} INFO - [2024-03-01 11:33:12,682] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:33:12,913] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:33:12,921] {logging_mixin.py:115} INFO - [2024-03-01 11:33:12,920] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:33:12,931] {logging_mixin.py:115} INFO - [2024-03-01 11:33:12,931] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:33:12,949] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.271 seconds
[2024-03-01 11:33:43,483] {processor.py:153} INFO - Started process (PID=25192) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:33:43,487] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:33:43,488] {logging_mixin.py:115} INFO - [2024-03-01 11:33:43,488] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:33:43,705] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:33:43,713] {logging_mixin.py:115} INFO - [2024-03-01 11:33:43,713] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:33:43,724] {logging_mixin.py:115} INFO - [2024-03-01 11:33:43,724] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:33:43,737] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.256 seconds
[2024-03-01 11:34:15,050] {processor.py:153} INFO - Started process (PID=25314) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:34:15,052] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:34:15,052] {logging_mixin.py:115} INFO - [2024-03-01 11:34:15,052] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:34:15,287] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:34:15,299] {logging_mixin.py:115} INFO - [2024-03-01 11:34:15,299] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:34:15,315] {logging_mixin.py:115} INFO - [2024-03-01 11:34:15,315] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:34:15,330] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.281 seconds
[2024-03-01 11:34:49,194] {processor.py:153} INFO - Started process (PID=25445) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:34:49,195] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:34:49,195] {logging_mixin.py:115} INFO - [2024-03-01 11:34:49,195] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:34:49,413] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:34:49,421] {logging_mixin.py:115} INFO - [2024-03-01 11:34:49,420] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:34:49,432] {logging_mixin.py:115} INFO - [2024-03-01 11:34:49,431] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:34:49,449] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.257 seconds
[2024-03-01 11:35:24,785] {processor.py:153} INFO - Started process (PID=25582) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:35:24,789] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:35:24,790] {logging_mixin.py:115} INFO - [2024-03-01 11:35:24,789] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:35:25,004] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:35:25,012] {logging_mixin.py:115} INFO - [2024-03-01 11:35:25,012] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:35:25,022] {logging_mixin.py:115} INFO - [2024-03-01 11:35:25,022] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:35:25,040] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.257 seconds
[2024-03-01 11:35:56,270] {processor.py:153} INFO - Started process (PID=25705) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:35:56,271] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:35:56,271] {logging_mixin.py:115} INFO - [2024-03-01 11:35:56,271] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:35:56,505] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:35:56,513] {logging_mixin.py:115} INFO - [2024-03-01 11:35:56,513] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:35:56,523] {logging_mixin.py:115} INFO - [2024-03-01 11:35:56,523] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:35:56,538] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.270 seconds
[2024-03-01 11:36:26,739] {processor.py:153} INFO - Started process (PID=25827) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:36:26,743] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:36:26,744] {logging_mixin.py:115} INFO - [2024-03-01 11:36:26,743] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:36:26,977] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:36:26,985] {logging_mixin.py:115} INFO - [2024-03-01 11:36:26,985] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:36:26,997] {logging_mixin.py:115} INFO - [2024-03-01 11:36:26,996] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:36:27,011] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.275 seconds
[2024-03-01 11:37:00,624] {processor.py:153} INFO - Started process (PID=25958) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:37:00,628] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:37:00,628] {logging_mixin.py:115} INFO - [2024-03-01 11:37:00,628] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:37:00,877] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:37:00,885] {logging_mixin.py:115} INFO - [2024-03-01 11:37:00,885] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:37:00,897] {logging_mixin.py:115} INFO - [2024-03-01 11:37:00,897] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:37:00,914] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.292 seconds
[2024-03-01 11:37:35,370] {processor.py:153} INFO - Started process (PID=26096) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:37:35,374] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:37:35,375] {logging_mixin.py:115} INFO - [2024-03-01 11:37:35,375] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:37:35,617] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:37:35,625] {logging_mixin.py:115} INFO - [2024-03-01 11:37:35,624] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:37:35,635] {logging_mixin.py:115} INFO - [2024-03-01 11:37:35,635] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:37:35,650] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.282 seconds
[2024-03-01 11:38:12,605] {processor.py:153} INFO - Started process (PID=26240) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:38:12,606] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:38:12,607] {logging_mixin.py:115} INFO - [2024-03-01 11:38:12,607] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:38:12,829] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:38:12,837] {logging_mixin.py:115} INFO - [2024-03-01 11:38:12,837] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:38:12,848] {logging_mixin.py:115} INFO - [2024-03-01 11:38:12,848] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:38:12,864] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.261 seconds
[2024-03-01 11:38:45,326] {processor.py:153} INFO - Started process (PID=26365) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:38:45,331] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:38:45,331] {logging_mixin.py:115} INFO - [2024-03-01 11:38:45,331] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:38:45,553] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:38:45,560] {logging_mixin.py:115} INFO - [2024-03-01 11:38:45,560] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:38:45,571] {logging_mixin.py:115} INFO - [2024-03-01 11:38:45,571] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:38:45,587] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.262 seconds
[2024-03-01 11:39:19,003] {processor.py:153} INFO - Started process (PID=26495) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:39:19,004] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:39:19,005] {logging_mixin.py:115} INFO - [2024-03-01 11:39:19,005] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:39:19,312] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:39:19,322] {logging_mixin.py:115} INFO - [2024-03-01 11:39:19,321] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:39:19,336] {logging_mixin.py:115} INFO - [2024-03-01 11:39:19,336] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:39:19,353] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.352 seconds
[2024-03-01 11:39:54,161] {processor.py:153} INFO - Started process (PID=26632) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:39:54,166] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:39:54,166] {logging_mixin.py:115} INFO - [2024-03-01 11:39:54,166] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:39:54,381] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:39:54,388] {logging_mixin.py:115} INFO - [2024-03-01 11:39:54,388] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:39:54,400] {logging_mixin.py:115} INFO - [2024-03-01 11:39:54,400] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:39:54,416] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.256 seconds
[2024-03-01 11:40:25,048] {processor.py:153} INFO - Started process (PID=26755) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:40:25,049] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:40:25,050] {logging_mixin.py:115} INFO - [2024-03-01 11:40:25,050] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:40:25,287] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:40:25,294] {logging_mixin.py:115} INFO - [2024-03-01 11:40:25,294] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:40:25,306] {logging_mixin.py:115} INFO - [2024-03-01 11:40:25,306] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:40:25,323] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.277 seconds
[2024-03-01 11:40:56,011] {processor.py:153} INFO - Started process (PID=26875) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:40:56,015] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:40:56,016] {logging_mixin.py:115} INFO - [2024-03-01 11:40:56,016] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:40:56,235] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:40:56,242] {logging_mixin.py:115} INFO - [2024-03-01 11:40:56,242] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:40:56,253] {logging_mixin.py:115} INFO - [2024-03-01 11:40:56,253] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:40:56,270] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.261 seconds
[2024-03-01 11:41:30,232] {processor.py:153} INFO - Started process (PID=27007) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:41:30,234] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:41:30,235] {logging_mixin.py:115} INFO - [2024-03-01 11:41:30,235] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:41:30,453] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:41:30,460] {logging_mixin.py:115} INFO - [2024-03-01 11:41:30,460] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:41:30,471] {logging_mixin.py:115} INFO - [2024-03-01 11:41:30,471] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:41:30,488] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.258 seconds
[2024-03-01 11:42:01,795] {processor.py:153} INFO - Started process (PID=27131) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:42:01,796] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:42:01,796] {logging_mixin.py:115} INFO - [2024-03-01 11:42:01,796] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:42:02,226] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:42:02,243] {logging_mixin.py:115} INFO - [2024-03-01 11:42:02,243] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:42:02,260] {logging_mixin.py:115} INFO - [2024-03-01 11:42:02,260] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:42:02,280] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.487 seconds
[2024-03-01 11:42:33,012] {processor.py:153} INFO - Started process (PID=27251) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:42:33,016] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:42:33,017] {logging_mixin.py:115} INFO - [2024-03-01 11:42:33,017] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:42:33,233] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:42:33,241] {logging_mixin.py:115} INFO - [2024-03-01 11:42:33,240] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:42:33,251] {logging_mixin.py:115} INFO - [2024-03-01 11:42:33,251] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:42:33,268] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.257 seconds
[2024-03-01 11:43:04,106] {processor.py:153} INFO - Started process (PID=27373) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:43:04,108] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:43:04,109] {logging_mixin.py:115} INFO - [2024-03-01 11:43:04,109] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:43:04,335] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:43:04,342] {logging_mixin.py:115} INFO - [2024-03-01 11:43:04,342] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:43:04,354] {logging_mixin.py:115} INFO - [2024-03-01 11:43:04,353] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:43:04,368] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.264 seconds
[2024-03-01 11:43:34,715] {processor.py:153} INFO - Started process (PID=27493) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:43:34,719] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:43:34,720] {logging_mixin.py:115} INFO - [2024-03-01 11:43:34,720] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:43:34,942] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:43:34,951] {logging_mixin.py:115} INFO - [2024-03-01 11:43:34,951] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:43:34,964] {logging_mixin.py:115} INFO - [2024-03-01 11:43:34,964] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:43:34,980] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.267 seconds
[2024-03-01 11:44:09,654] {processor.py:153} INFO - Started process (PID=27623) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:44:09,658] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:44:09,659] {logging_mixin.py:115} INFO - [2024-03-01 11:44:09,659] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:44:09,876] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:44:09,885] {logging_mixin.py:115} INFO - [2024-03-01 11:44:09,885] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:44:09,896] {logging_mixin.py:115} INFO - [2024-03-01 11:44:09,896] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:44:09,914] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.262 seconds
[2024-03-01 11:44:42,245] {processor.py:153} INFO - Started process (PID=27755) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:44:42,247] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:44:42,247] {logging_mixin.py:115} INFO - [2024-03-01 11:44:42,247] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:44:42,468] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:44:42,475] {logging_mixin.py:115} INFO - [2024-03-01 11:44:42,475] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:44:42,486] {logging_mixin.py:115} INFO - [2024-03-01 11:44:42,486] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:44:42,501] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.258 seconds
[2024-03-01 11:45:14,898] {processor.py:153} INFO - Started process (PID=27884) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:45:14,900] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:45:14,900] {logging_mixin.py:115} INFO - [2024-03-01 11:45:14,900] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:45:15,114] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:45:15,122] {logging_mixin.py:115} INFO - [2024-03-01 11:45:15,122] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:45:15,133] {logging_mixin.py:115} INFO - [2024-03-01 11:45:15,133] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:45:15,151] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.255 seconds
[2024-03-01 11:45:48,894] {processor.py:153} INFO - Started process (PID=28016) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:45:48,895] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:45:48,896] {logging_mixin.py:115} INFO - [2024-03-01 11:45:48,896] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:45:49,113] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:45:49,120] {logging_mixin.py:115} INFO - [2024-03-01 11:45:49,120] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:45:49,132] {logging_mixin.py:115} INFO - [2024-03-01 11:45:49,132] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:45:49,155] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.263 seconds
[2024-03-01 11:46:23,322] {processor.py:153} INFO - Started process (PID=28148) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:46:23,326] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:46:23,326] {logging_mixin.py:115} INFO - [2024-03-01 11:46:23,326] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:46:23,552] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:46:23,560] {logging_mixin.py:115} INFO - [2024-03-01 11:46:23,560] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:46:23,572] {logging_mixin.py:115} INFO - [2024-03-01 11:46:23,572] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:46:23,590] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.270 seconds
[2024-03-01 11:46:55,928] {processor.py:153} INFO - Started process (PID=28278) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:46:55,932] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:46:55,932] {logging_mixin.py:115} INFO - [2024-03-01 11:46:55,932] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:46:56,148] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:46:56,156] {logging_mixin.py:115} INFO - [2024-03-01 11:46:56,156] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:46:56,166] {logging_mixin.py:115} INFO - [2024-03-01 11:46:56,166] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:46:56,183] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.257 seconds
[2024-03-01 11:47:27,027] {processor.py:153} INFO - Started process (PID=28400) to work on /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:47:27,029] {processor.py:641} INFO - Processing file /home/luan/Documents/airflowalura/dags/dados_climaticos.py for tasks to queue
[2024-03-01 11:47:27,029] {logging_mixin.py:115} INFO - [2024-03-01 11:47:27,029] {dagbag.py:507} INFO - Filling up the DagBag from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:47:27,333] {processor.py:651} INFO - DAG(s) dict_keys(['dados_climaticos']) retrieved from /home/luan/Documents/airflowalura/dags/dados_climaticos.py
[2024-03-01 11:47:27,346] {logging_mixin.py:115} INFO - [2024-03-01 11:47:27,346] {dag.py:2379} INFO - Sync 1 DAGs
[2024-03-01 11:47:27,363] {logging_mixin.py:115} INFO - [2024-03-01 11:47:27,363] {dag.py:2927} INFO - Setting next_dagrun for dados_climaticos to 2022-11-28T00:00:00+00:00, run_after=2022-12-05T00:00:00+00:00
[2024-03-01 11:47:27,383] {processor.py:161} INFO - Processing /home/luan/Documents/airflowalura/dags/dados_climaticos.py took 0.357 seconds
